### ISSUE TITLE
What is the license applied to this repo?

### ISSUE THREAD

**Issue by ifraixedes** [jlord/reporobot#25]
Hi,

I would like to know what is/are the license/s applied to the repository?
Please can you specify it/them? it would be very useful if somebody decide to use it (e.g. barcelona-js/gitup#20).

Many thanks.

**Comment by ifraixedes** [comment]
OK, my fault, I got it, is in `package.json`, can you add at least a notice in README? thanks

**Comment by jlord** [comment]
Yep! Adding it now :sparkles: thanks!

**Comment by ifraixedes** [comment]
Good, however you forgot to update the license pattern, you know "year", etc..
Thanks.

**Comment by jlord** [comment]
Whooooops :blush: taken care of it, thanks!
