### ISSUE TITLE
Not drawing pictures

### ISSUE THREAD

**Issue by jlord** [jlord/reporobot#33]
I noticed that ~2 months ago @reporobot stopped drawing 🎨 and I have no idea why 🎉 

Cross ref: 🔗 https://github.com/jlord/patchwork/issues/16453

**Comment by jlord** [comment]
The GitHub API repo invites changed and so the invites weren't being accepted and the 🎨 wasn't being drawn. Fixed now! 

https://github.com/jlord/reporobot/pull/35

**Comment by GordieR** [comment]
I see this is closed, but I have the same issue
<img width="570" alt="terminal-screenshot" src="https://user-images.githubusercontent.com/46149560/50574986-47190680-0da8-11e9-8c90-c1493949aaee.png">
<img width="980" alt="git-it-screenshot" src="https://user-images.githubusercontent.com/46149560/50574988-4d0ee780-0da8-11e9-8c6a-ef3d6f3a94b6.png">
